before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
